# Generated by Django 6.0.5 on 2026-06-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 3 months', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills_required',
            field=models.CharField(blank=True, help_text='Comma separated skills', max_length=500),
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.CharField(blank=True, help_text='e.g. Rs. 10,000/month', max_length=100),
        ),
    ]
